# Generated by Django 4.1.5 on 2023-07-26 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApp', '0006_remove_userprofile_bio_remove_userprofile_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='hoobie',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='lname',
        ),
        migrations.DeleteModel(
            name='Hobbies',
        ),
    ]
