# Generated by Django 4.1.5 on 2023-07-26 16:44

import authenticationApp.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApp', '0007_remove_userprofile_age_remove_userprofile_fname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='token',
            field=models.CharField(default=authenticationApp.functions.generate_token, max_length=32, unique=True),
        ),
    ]
